const config = {
    theme: {
        extend: {
            fontFamily: {
                sans: ["var(--font-montserrat)", "sans-serif"],
                heading: ["var(--font-eb-garamond)", "serif"],
                "body-lg": ["Montserrat"],
                "headline-lg-mobile": ["EB Garamond"],
                "headline-lg": ["EB Garamond"],
                "label-md": ["Montserrat"],
                "body-md": ["Montserrat"],
                "headline-xl": ["EB Garamond"],
                "headline-md": ["EB Garamond"],
                "label-sm": ["Montserrat"],
            },
            colors: {
                violet: "hsl(var(--violet) / <alpha-value>)",
                "violet-light": "hsl(var(--violet-light) / <alpha-value>)",
                emerald: "hsl(var(--emerald) / <alpha-value>)",
                "emerald-light": "hsl(var(--emerald-light) / <alpha-value>)",
                saint: "hsl(var(--saint) / <alpha-value>)",
                "saint-light": "hsl(var(--saint-light) / <alpha-value>)",
                // New colors from snippet
                primary: "#000000",
                "on-primary-container": "#888380",
                "surface-container": "#f0eee9",
                "error-container": "#ffdad6",
                "on-tertiary": "#ffffff",
                "on-error-container": "#93000a",
                "secondary-container": "#fed977",
                "outline-variant": "#d0c4be",
                "primary-container": "#1e1b19",
                "on-secondary-fixed": "#241a00",
                "on-surface": "#1b1c19",
                "tertiary-fixed-dim": "#cbc5c3",
                "on-tertiary-fixed-variant": "#494644",
                "surface-tint": "#625d5b",
                "inverse-primary": "#ccc5c2",
                "primary-fixed-dim": "#ccc5c2",
                "outline": "#7e7570",
                "tertiary": "#000000",
                "on-error": "#ffffff",
                "tertiary-fixed": "#e8e1df",
                "on-primary-fixed-variant": "#4a4643",
                "surface-container-highest": "#e4e2dd",
                "surface-container-high": "#eae8e3",
                "primary-fixed": "#e9e1dd",
                "inverse-surface": "#30312e",
                background: "#fbf9f4",
                "surface-variant": "#e4e2dd",
                "on-tertiary-fixed": "#1d1b1a",
                "surface-dim": "#dbdad5",
                "on-surface-variant": "#4d4540",
                "on-secondary-container": "#785d00",
                "on-tertiary-container": "#888381",
                "surface-container-low": "#f5f3ee",
                "secondary-fixed": "#ffe08f",
                "secondary-fixed-dim": "#e6c364",
                secondary: "#755b00",
                "on-secondary": "#ffffff",
                "surface-bright": "#fbf9f4",
                "inverse-on-surface": "#f2f1ec",
                "on-primary": "#ffffff",
                "on-background": "#1b1c19",
                "surface-container-lowest": "#ffffff",
                "on-secondary-fixed-variant": "#584400",
                "tertiary-container": "#1d1b1a",
                "on-primary-fixed": "#1e1b19",
                surface: "#fbf9f4",
                error: "#ba1a1a",
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem",
            },
            spacing: {
                gutter: "24px",
                unit: "8px",
                "container-max": "1200px",
                "margin-mobile": "20px",
                "margin-desktop": "64px",
            },
            fontSize: {
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
                "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "500" }],
                "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "500" }],
                "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
                "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "500" }],
                "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
                "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
            },
            content: ["src/**/*.{js,ts,jsx,tsx,md,mdx}"],
        },
    },
};

export default config;