name: CI - Code Quality

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  fullstack:
    name: Fullstack
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"
          cache: npm
          cache-dependency-path: src/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type Check
        run: npm run typecheck

      - name: Build
        run: npm run build